project:
  type: website
  output-dir: docs

website:
  title: "Jie Geng | Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: coursework.qmd
        text: Coursework

format:
  html:
    theme:
      - cosmo
      - brand
    css: style.css
    toc: true
